version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Installing Paypal-REST-SDK
      - pip install paypalrestsdk
      - echo Compiling the Python code...
      - python create-payment.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - create-payment.py
